### ISSUE TITLE
VR rendering broken since latest update(s)

### ISSUE THREAD

**Issue by toxieainc** [vpinball/vpvr#13]
@vbousquet Please see https://www.vpforums.org/index.php?showtopic=48518&page=7#entry502516

**Comment by studlygoorite** [comment]
Also see here for v123 testing results https://www.vpforums.org/index.php?showtopic=48518&page=8#entry502658

**Comment by vbousquet** [comment]
From the reports at VPF, I understand that the fix are working well (the initial report was a user error between the exe if I get it well) with a side effect regarding the overall table being brighter. I will continue with the codebase merging (rendertarget & sampler, stereo fix, then shader uniforms & states management,...) isnce I think it needs to be updated to the latest postprocess to make fair comparisons (for example the bloom filter is not the same so differences are quite logical) and at worst, making things 'darker' like before can be hacked at the end (lights were hacked by multiplying by a lowering factor).

**Comment by studlygoorite** [comment]
> From the reports at VPF, I understand that the fix are working well (the initial report was a user error between the exe if I get it well) with a side effect regarding the overall table being brighter. I will continue with the codebase merging (rendertarget & sampler, stereo fix, then shader uniforms & states management,...) isnce I think it needs to be updated to the latest postprocess to make fair comparisons (for example the bloom filter is not the same so differences are quite logical) and at worst, making things 'darker' like before can be hacked at the end (lights were hacked by multiplying by a lowering factor).

I am going to have to apologize, I noticed that the tables that I had issues with I had earlier gone into and adjusted the day/night slider to brighten them up a little. Bringing that slider back down to default settings fixed the issues with these tables. I tested another 20 or so tables and could not find fault with any.....other than one, WWF is still slightly washed out, maybe a re-download would fix that as I don't know why just one table out of 50/60 would have this issue. So v123 could be the one :) thanks

**Comment by studlygoorite** [comment]
@vbousquet 
FYI, I posted this on VPForums,

Discord user Dondi found a bug with v123, "with tables authored in VPX 10.6. Looks like anything on the backglass in the HMD have the RED and BLUE color channels swapped" I also see the same issue. Thanks

**Comment by studlygoorite** [comment]
Further to this, it looks like the issue started with v94 as v81 was fine.

**Comment by studlygoorite** [comment]
More info, looks like the red and blue switch happens with pup packs only while viewing them in the headset.

**Comment by toxieainc** [comment]
Also there seems to be a problem with DMDs and B2S in VR mode now: https://www.vpforums.org/index.php?showtopic=48518&page=8#entry502852

**Comment by studlygoorite** [comment]
> Also there seems to be a problem with DMDs and B2S in VR mode now: https://www.vpforums.org/index.php?showtopic=48518&page=8#entry502852

I was under the impression that if the table was "not" optimized for VR like a VR Room is, then missing DMDs and backglasses was a common thing and that's why the tables get optimized, I will reply to RYSr

**Comment by toxieainc** [comment]
His answer on the thread indicates it has worked before: 'Yes they have always worked, back in the VPVR10.6 version all the way up to the VPVR 10.7 v102..'

**Comment by jreiman** [comment]
I can also confirm the VR DMD red/blue color swap issue starting in release 102 and still present in release 121.  Red shows as blue and vice versa.  Release 60 works normally.  I am not using any PUP pack and I have B2S disabled.

**Comment by toxieainc** [comment]
@vbousquet So only the DMD & B2S issue (see above) remains for this issue: https://www.vpforums.org/index.php?showtopic=48518&page=8#entry502852

**Comment by toxieainc** [comment]
Regarding that issue: "VPVR version 67 is the last version I have that they still worked as in previous versions. They were also working in version102 but had the color reversal in the DMD and the Back glass."

**Comment by toxieainc** [comment]
Is the B2S problem due to some B2S changes @JockeJarre ?

**Comment by toxieainc** [comment]
(see https://www.vpforums.org/index.php?showtopic=48518&p=504013 )

**Comment by JockeJarre** [comment]
> Is the B2S problem due to some B2S changes @JockeJarre ?

if VPVR expects the B2S Windows to contain "Form1" then that will be the problem. I can rollback all changes like this the coming days, if it helps. (though I would prefer proper naming of the screens)

**Comment by toxieainc** [comment]
No problem, i could just change the detection then. (try both)
What is the new name then?

**Comment by jsm174** [comment]
Maybe it's `B2S Background` or `B2S Backglass Server`?

https://github.com/vpinball/b2s-backglass/commit/1968dc8eab1e5dc2ddfac0b75a43a794afd827c9#diff-9a41b704a061cf648810f50699791c26f3d2e606c02d68a9c1f6479466f8a716R385 ?

**Comment by JockeJarre** [comment]
Yes as jsm174 states,

it depends if started with a background picture -> "B2S Background" or just
plain without background -> "B2S Backglass Server"

The reason for the name change is that if a Background Picture is selected it get's the name "B2S Backglass Server" as form owner. I would not expect this to be the case when run in VPVR? I mean no background selected. 
-> If that is the case only "B2S Backglass Server" would be the only window title to look for.

Then there is a third DMD form when there is a 3 window B2S. This used to be a form without name. It is now named "B2S DMD"
If that is ok for you, I'll leave it this way for now. Tell me if you want me to just keep one name.
Is there any chance for me to test VPVR without 3D glasses?

**Comment by toxieainc** [comment]
Yes, VPVR also works in normal 2D mode. I will try to wire up the new names then. Thanks!

**Comment by toxieainc** [comment]
I just added all these 3 names to the window search list

**Comment by vbousquet** [comment]
Render is now good again, except pup pack bug which is tracked in another issue, and minor differences (AO,...) which are also tracked on other issues, so I will close this one for now
