### ISSUE TITLE
Massive crashes in VPinballX_GL-10.7.1-131-x86

### ISSUE THREAD

**Issue by Joey-2001** [vpinball/vpvr#16]
I try to convert a table in VR and have today more than a dotzend crashes.
I open the table in the version, edit a few things, start the table in VR to see, how it looks.
At the latest after the second start and finish of the table VPXVR crashed.
I use Win 10.1 with all the latest updates. I completely checked my computer today, to rule out a computer problem; everything is perfect.
Minidumps are not created on crash.
Attached are some of the crash.txt.
[crash.zip](https://github.com/vpinball/vpvr/files/9220860/crash.zip)

**Comment by toxieainc** [comment]
Do you have the table in question for us?

**Comment by Joey-2001** [comment]
Sorry; can't remember. Maybe it was a problem with my system. I install new from scratch and till now, I only have found the table, I mentioned in the other issue. So I think, I close this one. If I find another one, I post a new one.

**Comment by toxieainc** [comment]
Would have been interesting, as the call stack in your crash.zip is weird. Never seen that before.
