### ISSUE TITLE
10.7.133 glCheckFramebufferStatus returned 0x00

### ISSUE THREAD

**Issue by psiomicron** [vpinball/vpvr#18]
When running tables in 10.7.133 after about 3 to 4 runs it will return an error on the next run and crash:

glCheckFramebufferStatus returned 0x00
GL_FRAMBUFFER_INCOMPLETE_ATTACHMENT

Using Pimax headset in steamvr, and a pinsim. 

Thanks

**Comment by vbousquet** [comment]
Fix with v266 (tested by Sixtoe who had made the same issue report) si closing
