### ISSUE TITLE
A table that always crashes in the versions from VPinballX_GL-10.7.1-131-x86 to VPinballX_GL-10.7.1-139-x86

### ISSUE THREAD

**Issue by Joey-2001** [vpinball/vpvr#19]
I have tested all 130 versions with this table that I am converting (see link).
It crashes in every version of the program. The table is loaded in the editor. I press F5 and when the Visual Pinball Player is visible, the program crashes after two to three seconds.
There are no error messages; I have attached the crash.txt file.
The table runs with the normal VPX version 222 without any problems.
I also tested it with the VR version VPinballX_GL-10.7.1-110-x86. Also in that version it starts normally and does not crash.
Everything I have done on two computers. The course is identical on both computers.

VPinballX_GL-10.7.1-110-x86 - works
VPinballX_GL-10.7.1-131-x86 to VPinballX_GL-10.7.1-139-x86 - crashes

[crash.txt](https://github.com/vpinball/vpvr/files/9386614/crash.txt)

Table: https://mega.nz/file/EY9AWKAC#oW5R5ng0p41eZOweyVSWlwnQxVoN4WZQwV8Y88AEvDw

**Comment by toxieainc** [comment]
Can repro, will try to find out whats happening.

**Comment by toxieainc** [comment]
So far only found/fixed another (7 year old) bug with wire ramps.  ;)

Your issue is related to one specific ramp, but no clue how it even happens.  :/

**Comment by toxieainc** [comment]
@Joey-2001 Is this on a NVIDIA laptop? Or desktop NVIDIA GPU?

**Comment by Joey-2001** [comment]
First PC has a GeForce 3080ti, second one has a GeForce 2080ti.

**Comment by toxieainc** [comment]
Okay, found it by now. This one was a tricky one. Extremely weird that no other table or table element triggered this before. Seems like you're the only one to ever use a 3 Wire Left Ramp in VPVR building/testing.   ;)

**Comment by Joey-2001** [comment]
Great, you found it. It's not my table, but I can tell remdwaas, what the problem is.
Can you solve this in new version?

**Comment by toxieainc** [comment]
Yup, will do this evening.

**Comment by toxieainc** [comment]
New prerelease will be available in a few minutes
