### ISSUE TITLE
VPVR Broken Since v144

### ISSUE THREAD

**Issue by studlygoorite** [vpinball/vpvr#22]
Note v56, 60 and 63 are not working, just get a black screen when loading a table. Using Oculus Quest 2 with RTX 3080

**Comment by vbousquet** [comment]
My bad (latest change moving to rendertargets & samplers). I will work a fix for this asap.
Sorry for the inconvenience

**Comment by vbousquet** [comment]
This was a very stupid syntax mistake (forgot two parenthesis....). Fix has been prepared and should get it working back when merged.

**Comment by studlygoorite** [comment]
> This was a very stupid syntax mistake (forgot two parenthesis....). Fix has been prepared and should get it working back when merged.

Nice, thank you!!

**Comment by studlygoorite** [comment]
FYI, v165 has fixed the black screen but now has an issue in that the playfield is black on the cabinet for 10.7 tables but you can see two copies of the proper colored playfield floating off to the side in each eye :)  Pics are here https://drive.google.com/drive/folders/1bEp9e-m21j2NO0YCkVt3LZN_nVIW34v3?usp=sharing
