### ISSUE TITLE
v165 Issue

### ISSUE THREAD

**Issue by studlygoorite** [vpinball/vpvr#24]
I posted this in the closed thread by mistake, re posting here...

FYI, v165 has fixed the black screen but now has an issue in that the playfield is black on the cabinet for 10.7 tables but you can see two copies of the proper colored playfield floating off to the side in each eye :) Pics are here https://drive.google.com/drive/folders/1bEp9e-m21j2NO0YCkVt3LZN_nVIW34v3?usp=sharing

Also, I hate to say this but it looks like the bright bulb issue is worse.

I can get others to confirm if needed

**Comment by vbousquet** [comment]
This one is different and will be somewhat difficult since I have tested and it works on desktop in all modes. So this is a VR only bug. I will investigate but this may take longer. Thanks a lot for your testing efforts!

**Comment by studlygoorite** [comment]
Thank you, I will share this information with a bunch of VR developers on the VR Pinball Group Discord to see if anyone can help pinpoint a cause/remedy.

**Comment by studlygoorite** [comment]
Sixtoe took a look at the pics and though if he was to take a complete guess it would have something to do with there being 2 mesh playfields, dunno if this helps but I'll throw anything I can at you :)

**Comment by vbousquet** [comment]
This should be fixed as of version v266 so I will close this issue for now
