### ISSUE TITLE
Not reading correct resolution of second display.

### ISSUE THREAD

**Issue by psiomicron** [vpinball/vpvr#26]
In 10.6 if there is a second HDMI it'll read the correct resolution for the second display (based off windows settings). On 10.7 its reading the same resolution as the first display (way to high in my case). When trying to select the correct resolution in the settings, the table will error out with the following error a few seconds after ball launch:

"Capture: Received DXGI_ERROR_WAIT_TIMEOUT"

Thanks for all you guys done thus far!

**Comment by vbousquet** [comment]
Tested and worked in latest version. So I'm closing for now. If you are still facing the problem, please re-open

**Comment by psiomicron** [comment]
Just ran 232... it seems to detect my second monitor as monitor 1 and my
first monitor as monitor 2. it's flipped. See attached screenshots. As you
can see vpx is showing monitor 1 with resolution of 1920 x1080 but that is
my second monitor resolution.
