### ISSUE TITLE
Ready for 10.7.2 release?

### ISSUE THREAD

**Issue by toxieainc** [vpinball/vpvr#28]
@fuzzelhjb @vbousquet @jsm174 : Are we ready in principal for a 10.7.1 release?

Before vbousquet brings back the larger merge with VPVR i'd like to release 10.7.1

(D'oh, should have gone to vpinball instead of vpvr :/ )

**Comment by vbousquet** [comment]
I think vpinball is ready for a release. I have other updates but they can (should) wait.
Regarding the version naming, I think this should be named 10.7.2 or it will be somewhat confusing.

**Comment by toxieainc** [comment]
Why would it be confusing? There was no 10.7.1 yet

**Comment by jsm174** [comment]
Any thoughts on removing upx compression on builds?

**Comment by vbousquet** [comment]
The prerelease were labelled 10.7.1 then 10.7.2 when playfield meshes where made optionally collidable.
This led up to have a file version at 1072 and in pintable.cpp, there is 
        ` if (loadfileversion < 1072) // playfield meshes were always forced as collidable until 10.7.1`
I think the file version is displayed when there are version mismatch. This might get confusing. Beside this internal version, I don't think the version was advertised as 10.7.2.

Or we could change the above code to use 1071 but this may cause problem to people using the prerelease.

**Comment by fuzzelhjb** [comment]
I think upx doesn't make any sense anymore. So I vote for removing it.

Vincent Bousquet ***@***.***> schrieb am So., 4. Sept. 2022,
22:44:

**Comment by toxieainc** [comment]
Hmmm.. Skipping 10.7.1 then.. ..
@fuzzelhjb Your opinion on that? And anything else from your side?

**Comment by fuzzelhjb** [comment]
I'm for 10.7.2 if the file format version is already on this version.

toxie ***@***.***> schrieb am Mo., 5. Sept. 2022, 09:51:

**Comment by toxieainc** [comment]
Okay, then i'll move this forward.

btw: Fascinating.. zip size of VPX github package now ~doubled without UPX compression.. (not that it matters much nowadays, but still interesting)

**Comment by toxieainc** [comment]
Done.. @fuzzelhjb Could you please add this 10.7.2 build to the beta thread?

**Comment by fuzzelhjb** [comment]
I will.. have you started the build already?

toxie ***@***.***> schrieb am Mo., 5. Sept. 2022, 12:01:

**Comment by fuzzelhjb** [comment]
Arg now I know why we used upx. The file size of the archive is too big for
vpforums. The limit is 30mb and now we are at 32mb

Christoph Schmidt ***@***.***> schrieb am Mo., 5. Sept. 2022,
12:10:

**Comment by fuzzelhjb** [comment]
I repacked it with 7zip and now it's just 19mb ;)

Christoph Schmidt ***@***.***> schrieb am Mo., 5. Sept. 2022,
12:58:

**Comment by fuzzelhjb** [comment]
And now vpforums doesn't allow such file format

Christoph Schmidt ***@***.***> schrieb am Mo., 5. Sept. 2022,
13:02:

**Comment by toxieainc** [comment]
Oh my.. ..

**Comment by freezy** [comment]
How about linking it to GitHub releases? Those are downloadable for everybody.

**Comment by fuzzelhjb** [comment]
Ah... Sure. It's always the simple things that are complicated ;)

freezy ***@***.***> schrieb am Mo., 5. Sept. 2022, 15:47:

**Comment by toxieainc** [comment]
Small update: There is still some quirk with VPX not starting up properly (see vpforums beta thread). This should be resolved first.

**Comment by vbousquet** [comment]
For the time being, I have delayed any commit on the VPX side to allow for the release (sort of a "feature freeze" or more "commit freeze"). Since the VPX release is somewhat delayed due to the not starting bug, and given that there have been significant work on the VPVR side, should I catch up on the VPX side ?

**Comment by toxieainc** [comment]
I fear that this is the best thing to do. I did not have any time so far to really track down the startup bug (only briefly) plus i'm currently mostly AFK.
I think we could simply just create a branch later-on and then merge a potential startup fix into that one.
So please go ahead with the catch up. Thanks!!!

**Comment by fuzzelhjb** [comment]
I'm not very active at the moment so a clear yes from my side.

toxie ***@***.***> schrieb am So., 4. Sept. 2022, 20:24:

**Comment by toxieainc** [comment]
Okay, all is in progress already. The only thing that remains weird is the mystery startup hang bug (that is worked around by building with v141_xp on Thalamus setup), and that on some setups some large tables don't load (only with this Thalamus special build though).
I'll give the testing ~one more week and then i'll go for a release.

**Comment by toxieainc** [comment]
..and released, thanks all!!
