### ISSUE TITLE
Playing in VR doesn't work since version 144.

### ISSUE THREAD

**Issue by Joey-2001** [vpinball/vpvr#29]
I tested the follwing versions with my Valve Index at SteamVR (Windows 10 64bit 10.0.19044 build 19044, GeForce 3080ti):
![grafik](https://user-images.githubusercontent.com/35002625/188848819-49dc33ee-78d8-4812-8b08-3a5f868b0761.png)
Testtable is "Red & Ted's Road Show (Williams 1994) VPinWorkshop 1.2".
After every test I closed Vpinball and take a look, if something is running in the taskmanager; but VP always closed fine in every version.
I doesn't change anything in Video/Graphics options.
In the preference VR settings I used my normal settings for the older versions.
For the newer versions I tested with settings for VR-preview with disabled (DIS), left eye (LE), right eye (RE) and both eyes (BE).
Result of all versions with the new VR-preview settings:
LE = Playfield-Monitor shows 2 Pictures (stereo), VR-Headset shows 2 Pictures (stereo) at the left eye, right eye is black.
RE = Playfield-Monitor is black, VR-Headset shows 2 Pictures (stereo) at the left eye, right eye is black.
BE = Playfield-Monitor shows 2 Pictures (stereo) on half of the screen and black on the other half, VR-Headset shows 2 Pictures (stereo) at the left eye, right eye is black.
DIS = Playfield-Monitor is black, VR-Headset shows 2 Pictures (stereo) at the left eye, right eye is black.
Versions 160 and 156 are completely black on playfield and in VR-Headset.
Then I tested the version 144 and this one works, as it should. It seems, that this is the last version, that could be used at the moment for playing in VR.
If I should test something else, send me a note.

Playfield+Headset with new versions
![grafik](https://user-images.githubusercontent.com/35002625/188853228-841ea66a-2846-4709-b16d-54f7b7cc1584.png)
Both eyes on playfield
![grafik](https://user-images.githubusercontent.com/35002625/188853410-0c495a66-25a0-42e7-a389-827350e5630b.png)

**Comment by vbousquet** [comment]
This should be fixed as of version v266 so I will close for now. If you still encounter problems, we will reopen it
