### ISSUE TITLE
Version 212 errors

### ISSUE THREAD

**Issue by ron66686** [vpinball/vpvr#32]
![rn_image_picker_lib_temp_98fa8013-12ee-4128-8da8-db5c416ca844](https://user-images.githubusercontent.com/69837431/189578847-8ce733c8-4ac0-48b8-8b6e-370051e9ae3a.jpg)
Errors version 212  looks like it looking for the shadergl files on d: drive while everything is on C:

**Comment by vbousquet** [comment]
Hi, thanks to the report. It was a stupid mistake I made (forgetting to push the latest Screen Space reflection file). It will be fixed as soon as PR https://github.com/vpinball/vpvr/pull/33 will be merged.
