### ISSUE TITLE
Crash if Dyn. AO and SSR active at same time

### ISSUE THREAD

**Issue by toxieainc** [vpinball/vpvr#35]
https://github.com/vpinball/vpvr/blob/master/pin/player.cpp#L4918 returns a nullptr then

**Comment by vbousquet** [comment]
Yes, should be GetReflectionBufferTexture(). Also, SSReflections are not yet tested and validated.
Will fix it in my next PR. It looks like I made too much toofast for my programming skills. I'm doing quality test right now (glsl validation, some perf and table rendering test,...) Hope it will help

**Comment by toxieainc** [comment]
No problem, thats simply what happens if doing such huge refactors.
And thats why you have testers and reviewers, too, to help find all corner case breakages.  :)

**Comment by vbousquet** [comment]
Closed by https://github.com/vpinball/vpvr/commit/7c8fe7c6be1eb85e6de75199369bfdae73bb08f5

**Comment by toxieainc** [comment]
Yup, works, thanks!
