### ISSUE TITLE
V219 and v220 No Go

### ISSUE THREAD

**Issue by studlygoorite** [vpinball/vpvr#36]
FYI, 

Just tried both and we get nothing but black on the desktop and VP X GL Loading hang on the headset for every table.

**Comment by vbousquet** [comment]
Could you post a screenshot of your VR and Video options ? 

In desktop mode, with the download from Github, I have all table opening and rendering fine in camera mode, and only issues with the remaining parts which were not yet tackled (mirror, SSRefl, SMAA) and static prerendered table (desktop mode). I don't know what is causing problem

**Comment by studlygoorite** [comment]
Sure thing
![Capture2](https://user-images.githubusercontent.com/87738258/189752583-4672c573-b0f5-4ffa-a06f-d99825f817d9.PNG)
![Capture](https://user-images.githubusercontent.com/87738258/189752589-ad763920-d681-48e1-ae56-ebc838f8f71a.PNG)

**Comment by studlygoorite** [comment]
Perhaps it's the same issue as with #22 that you fixed with v165 ? :)

**Comment by vbousquet** [comment]
Is it a VR only bug ? I mean, if you disable VR mode in VR Options, does it works in desktop mode ? (it should, but who knows...) It would help me to know where to hunt the bug

**Comment by studlygoorite** [comment]
With VR disabled some tables work like Bad Cats, Big Bang Bar and Cactus Canyon but most don't. Some will show with a black playfield while other elements are visible like bumpers, slings drop targets like Blackout, 300 and Big Shot . Any table with a pup pack the playfield is black and then the pup pack plays on the playfield but bumpers and slings and such are still visible :) Backing out of a table requires the regular "Q" twice but then you have to click the playfield with the mouse and then close the table edit box to shut it down.

**Comment by studlygoorite** [comment]
Note, v222 is still the same in VR, headset stuck on loading and a black desktop.

**Comment by vbousquet** [comment]
Could you have a go to v225. It is supposed to improve at least for desktop (still some known issue like slowdown for Blackout, some aliasing problems, missing SMAA, and missing mirror) but it is supposed to be able to run more or less any table beside this.

There were also some fixes on the VR side and it was reported to be running fine here: https://github.com/vpinball/vpvr/issues/38 So maybe this time it will look better ?

**Comment by studlygoorite** [comment]
> Could you have a go to v225. It is supposed to improve at least for desktop (still some known issue like slowdown for Blackout, some aliasing problems, missing SMAA, and missing mirror) but it is supposed to be able to run more or less any table beside this.
> 
> There were also some fixes on the VR side and it was reported to be running fine here: #38 So maybe this time it will look better ?

Thanks but unfortunately it's still the same for VR, stuck loading in the headset and a black screen on the desktop even with VR Preview enabled. Rolling back to v144 and everything works. Sorry for the bad news and thanks again for working on it. Ron66686 is in our Discord and I have asked others to test to make sure it's not just me, but I don't think so :)

**Comment by studlygoorite** [comment]
FYI, still the same issue for me and at least one other (same since v219), v232 shows black on the desktop and nothing will load in the headset. I have Quest 2 and the other person, psiomicron uses a Pimax headset. He wrote this, dunno if it will help....

"I have a feeling that it is detecting the headset as another monitor. If I unplug my monitor and hover the cursor over play then start it once unplugged my headset then goes to a black screen"

**Comment by vbousquet** [comment]
The latest one (v234) was made upon this report and is supposed to fix the black screen problem. Could you give it a try ?

**Comment by vbousquet** [comment]
Closing this issue since v264 it is now evaluated in https://github.com/vpinball/vpvr/issues/56
