### ISSUE TITLE
V222

### ISSUE THREAD

**Issue by ron66686** [vpinball/vpvr#38]
![IMG20220913111404](https://user-images.githubusercontent.com/69837431/189786070-25d0e946-112c-49be-b743-149994971b7c.jpg)
Running with these settings it seems to be up and running again still some over brightness on a few tables haven't done a big test yet but it's playable again

**Comment by vbousquet** [comment]
Nice and thanks for the report !
I still have quite a few things to fix but this is heading in the right direction. Could you share a copy of the Video options dialog as well to help me understand what is ok to what is not ? Also, I would be interested if you could point me to some of the overbright table to have a look (to understand if its VPVR or if the table author did add some overbright to compensate the fact that VPVR used to more or less disable scene lighting)

**Comment by vbousquet** [comment]
Cleaning up issue list, so closing since there is no issue here :)

**Comment by ron66686** [comment]
Tested with X-Men that's really bright and avatar the lights are really
bright
