### ISSUE TITLE
Editor /Player Crash on 2nd Table Launch

### ISSUE THREAD

**Issue by Sixtoe** [vpinball/vpvr#4]
If you load a table in the editor, launch it, then exit out to the editor, then launch the table again VPX crashes with;

Visual Pinball Error
glCheckFramebufferStatus returned 0x00
GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT

![image](https://user-images.githubusercontent.com/41960611/169344537-0bb4aa56-91d5-433e-a5f9-914d5d583ff4.png)

**Comment by vbousquet** [comment]
Fix with v266
