### ISSUE TITLE
SDL Window fills the whole screen (maximized) and not windowed.

### ISSUE THREAD

**Issue by psiomicron** [vpinball/vpvr#51]
SDL Window fills the whole screen (maximized) and not windowed causing the entire monitor to be black. This covers any B2S or Pupvideos from being displayed and shows entire backglass to be blacked out.

**Comment by vbousquet** [comment]
Could you post a screenshot of your video and VR settings ? also could you tell which version you are using (v245 ?). Thanks

**Comment by psiomicron** [comment]
I'm am using 245. I have attached some pic examples. First one is when I use the older version 142. You can see the b2s running and the SDL screen is windowed and sized down, also included us what it looks like in VR. The third pic is 245. The monitor is black because the SDL window is maximized, so I didn't take a picture of the monitor. I took a photo of what it looks like in VR as you can see the backglass is black. I did a ctrl tab so you can see the windows and the sdl is all black and not "windowed". Also included vrsettings for 245. (again the pics where it looks like it's working is in
ver 142, the ones where it's not is 245)

Also, side note, when I hit escape to exit I cannot close to editor, it
immediately minimizes to the tray when I click the button. When I click on
it again to expand and try to hit the button again it minimizes to the tray
again... maybe it's related to the SDL window being maximized?

**Comment by vbousquet** [comment]
I will have a detailled look to understand what's happening. Could you post the screenshots on GitHub. It looks like it did not accept them (I can not find them) ?

**Comment by psiomicron** [comment]
Here are the screenshots
![20220922_095337](https://user-images.githubusercontent.com/23017535/191867680-726db474-c35d-4960-8da9-036908ebf603.jpg)
![20220922_095356](https://user-images.githubusercontent.com/23017535/191867693-d314c3b6-9769-44c7-a949-7f0e5a3952c5.jpg)
![20220922_095459](https://user-images.githubusercontent.com/23017535/191867703-f25bcaea-102a-4025-8a33-a65cab6830be.jpg)
![20220922_095522](https://user-images.githubusercontent.com/23017535/191867715-5778cd6b-8904-4144-9649-1e50041d37ee.jpg)
![20220922_095721](https://user-images.githubusercontent.com/23017535/191867727-251872fc-5f6f-4dbf-84e5-f47285269996.jpg)

**Comment by retro27** [comment]
I have the same problem, I'm using 245, I have set all options to default and tried to reset the windows positions. but I get the black full screen, when in VR.

**Comment by psiomicron** [comment]
FYI v255 has the same issues as well

**Comment by vbousquet** [comment]
Should be solved by v264 so closing it for now
