### ISSUE TITLE
Some tables crash or have green lines on black background

### ISSUE THREAD

**Issue by psiomicron** [vpinball/vpvr#52]
Some tables like indiana jones hybrid table are just showing nothing but green lines on a black background. Attached is a photo.
![20220916_184803](https://user-images.githubusercontent.com/23017535/191613804-a1ab33cd-8ee3-4337-bea9-430041593abe.jpg)

Also
Some tables are just crashing at start, like Xmen and Addams Family vr rooms. After more attempts sometimes they will randomly run. But have more crashes than actual runs.

**Comment by vbousquet** [comment]
Which version are you using ? Latest v245 or another ?

**Comment by psiomicron** [comment]
The latest 245

**Comment by psiomicron** [comment]
FYI v255 has the same issue.

**Comment by studlygoorite** [comment]
Only found Congo to have this so far with v258

**Comment by vbousquet** [comment]
Should be solved by v264 so closing it for now
