### ISSUE TITLE
v281 brightness issues

### ISSUE THREAD

**Issue by psiomicron** [vpinball/vpvr#67]
v281 still has some brightness issues where tables are too bright, ie Xmen. have to bring the night cycle slider all the way to the left and it's better but still to bright. As you can see it also messes with the backglass image.
![20221008_091756](https://user-images.githubusercontent.com/23017535/194717376-f5253290-dca4-4506-99c3-8711cbe3c572.jpg)

**Comment by vbousquet** [comment]
Should be solved in latest
