### ISSUE TITLE
DMD missing or textbox wrong colors

### ISSUE THREAD

**Issue by toxieainc** [vpinball/vpvr#7]
@vbousquet Seems like there is still something off after your changes with DMDs and textboxes.

E.g. GB and FG both show only a black DMD and the builtin tables have the color channels of the textboxes flipped.

But i tested for example AFM and there the DMD seems to behave like expected.

**Comment by vbousquet** [comment]
I should have checked that too. It's quite logical, these are generated textures. I checked that they were ok with the data format, but did not check th channel ordering. I will fix that

**Comment by toxieainc** [comment]
No prob, thats why we test stuff.   :)
VPX/VR is a beast with maaany special cases nowadays.
